### ISSUE TITLE
Only records for like 5 seconds

### ISSUE THREAD

**Issue by Codewyvern** [jbanquo/chaturbate-downloader#1]
Not sure why its happening but the tickboxes stay on for 5 seconds and then unticked and the videos are all really small filesize.

**Comment by jbanquo** [comment]
It is very likely that one of the following is your issue:
* Your network connection is unstable
* Your CPU is under strenuous use while recording
* Chaturbate is having problems (I recommend checking their service status)
* Streamlink is having problems (I recommend checking their issues page)

If none of these are the case, try running it again today and see if its any better.

**Comment by jbanquo** [comment]
Update: It looks like it was either a chaturbate, or streamlink issue. See [this issue on steamlink](https://github.com/streamlink/streamlink/issues/1301).
