### ISSUE TITLE
Closes other processes

### ISSUE THREAD

**Issue by Talamatis** [jbanquo/chaturbate-downloader#2]
I've noticed, that when i have this program running, sometimes other programs on my computer will just get force closed.

I've seen this with the World of Warcraft client and with chrome browser.

I don't know how to gather more "evidence", all i know is when this program is running i have the problem, and it does not if i close this program.

**Comment by jbanquo** [comment]
Yes, I do know this issue exists but I am unsure why it is happening.

My current theory is that if you are tracking too many models, the high number of resources used causes other programs to crash. In this case, this issue would not be a bug.

The culprit program for me is Discord, and as you know it's based on the same technology as the chrome browser.

I have not worked on this project for a while but do expect some activity in the coming months.
